### ISSUE TITLE
Feature Request - Add headers button on the item sheet

### ISSUE THREAD

**Issue by p4535992** [trioderegion/archon#3]
Reluctantly I have to say that it is evident that your module is much better than the old [Forien Unidentified Items](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-unidentified-items).
The only thing that is still missing is the addition of the buttons on the sheet header other than in the context menu.

In a purely optional way if it were possible to add some color on the header sheet buttons.

**Comment by trioderegion** [comment]
I've been pondering similar things - you are absolutely correct.

The only reason I didn't put that feature into 1.1 is that the item sheet header is pretty prime real estate, so simply adding a button there felt a bit irresponsible without further consideration. Its good to know the use case is desired, however.

To help me decide on this UX issue, can you describe your workflow that is stopped/blocked by the absence of archon controls directly on item sheets? In other words, what was the situation that arose that made you look for item sheet archon controls?

Thanks for the kind words as well. Without FUI's influence on the community, this module likely would not exist 😄

**Comment by p4535992** [comment]
I personally find it useful when I have a masked item in the character's inventory or in a log quest, I just edit the item and look at the preview of the real item.

Also, I would like to convince others to stop using FUI, and this is one of the flaws that people have pointed out to me.

**Comment by trioderegion** [comment]
This usecase should now be covered in the 1.2.0 workflow update 👍
