### ISSUE TITLE
[feature] Notify GM when an archon item is equiped

### ISSUE THREAD

**Issue by Orionox** [trioderegion/archon#4]
either as a system notification or in the little archon menu, it would be nice if we knew when an item that had a secret identity was equipped.

**Comment by trioderegion** [comment]
Currently, Archon is entirely system agnostic and the concept of an "equipped" item is a system dependent concept. As it stands, something like this would be outside the scope of Archon.

That said, providing hooks or other ways for modules/systems to interact with Archon is a reasonable request 😄 . This will be more of a long-term development goal.
