### ISSUE TITLE
UI/UX: Improve Visual Clarity On Archon Menu for Editing Existing Archon Items

### ISSUE THREAD

**Issue by NickGrayInternational** [trioderegion/archon#5]
I was asked to post this here as a reminder for you from Discord.

**Comment by trioderegion** [comment]
Mockup from discussion 
![image](https://github.com/trioderegion/archon/assets/14878515/482f59e4-35bd-40f5-97db-1913cfb8962d)

"You may not like it, but this is peak design" Mockup
![image](https://github.com/trioderegion/archon/assets/14878515/46664c95-9a69-4f58-9ec8-078fa30e1134)
