### ISSUE TITLE
[ISSUE] Adding Archons Directly to Item Pile or Actor

### ISSUE THREAD

**Issue by Loloup** [trioderegion/archon#7]
1. Add Original Item to Actor Sheet
2. Open Archon UI
3. Drag Original Item from Actor Sheet to Top of Archon
4. Click Preserve Img
5. Change Item Name in the Bottom of Archon
6. Make Sure Add to is set to the Actor
7. Click Create Archon

All other modules are disabled.
DnD 5e System

**Comment by APence-XGEN** [comment]
also having this issue in dnd5e 4.0.4
