### ISSUE TITLE
[Feature Request] Add shortcuts

### ISSUE THREAD

**Issue by Nysterian** [trioderegion/archon#9]
What I'm mainly hoping for is a way to open the Archon Window without having to go to the items directory. But any other shortcuts would definitely be welcome.

This could be done through control keybinds, or by providing a list of macros that we can place onto our hotbar for ease of access.

**Comment by trioderegion** [comment]
The application is held in the module's namespace, so a macro to open it is fortunately pretty simple:

```js
new (game.modules.get('archon').ArchonControl)().render(true);
```

Keeping this issue open for further consideration.
